### ISSUE TITLE
kill -QUIT blows up goreman without sending signals on

### ISSUE THREAD

**Issue by grosser** [mattn/goreman#52]
```
## Install goreman
RUN \
  curl -sL https://github.com/mattn/goreman/releases/download/v0.0.10/goreman_linux_amd64.zip > /tmp/goreman.zip && \
  unzip -d /usr/bin /tmp/goreman.zip && rm /tmp/goreman.zip && \
  chmod +x /usr/bin/goreman
```

```
kill -QUIT <PID>
```

```
SIGQUIT: quit
PC=0x460e53 m=2

goroutine 0 [idle]:
runtime.futex(0x949b18, 0x0, 0x7f73ff299dc8, 0x0, 0x7f7300000000, 0x460b76, 0x3c, 0x0, 0x7f73ff299e10, 0x414b0b, ...)
	/goroot/src/runtime/sys_linux_amd64.s:388 +0x23
runtime.futexsleep(0x949b18, 0x0, 0xdf8475800)
	/goroot/src/runtime/os_linux.go:62 +0xd7
runtime.notetsleep_internal(0x949b18, 0xdf8475800, 0x1)
	/goroot/src/runtime/lock_futex.go:174 +0xeb
runtime.notetsleep(0x949b18, 0xdf8475800, 0x7f01)
	/goroot/src/runtime/lock_futex.go:194 +0x56
runtime.sysmon()
	/goroot/src/runtime/proc.go:3618 +0x14c
runtime.mstart1()
	/goroot/src/runtime/proc.go:1126 +0x11e
runtime.mstart()
	/goroot/src/runtime/proc.go:1096 +0x64

goroutine 1 [chan receive]:
main.startProcs(0x18, 0x7d2278)
	/gopath/src/github.com/mattn/goreman/proc.go:88 +0x24d
main.start(0xc4201300f0, 0x5, 0x7a0bdb)
	/gopath/src/github.com/mattn/goreman/goreman.go:175 +0x1db
main.main()
	/gopath/src/github.com/mattn/goreman/goreman.go:219 +0x553

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:2086 +0x1
```

**Comment by grosser** [comment]
no longer using this, switched to https://grosser.it/2018/05/02/running-multiple-commands-in-docker-in-parallel
